[package]
name = "_TestRunner"
version = "0.1.0"
edition = "2024"

[dependencies]
nix = "0.30.0"
serde = { version="1.0.219", features = ["derive"]}
termion = "4.0.5"
threadpool = "1.8.1"
toml = "0.8.23"
walkdir = "2.5.0"
